spring:
  datasource:
    master:
      jdbcUrl: jdbc:mysql://localhost:3306/test
      username: root
      password: root
    slave:
      jdbcUrl: jdbc:mysql://localhost:3307/test
      username: root
      password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

